parent_endpoint = "http://127.0.0.1:8000/api/resources/"

image_list_endpoint = "images/"
flavor_list_endpoint = "flavors/"
network_list_endpoint = "networks/"
subnet_list_endpoint = "subnets/"
floating_ip_list_endpoint = "floating-ip/"
router_list_endpoint = "routers/"
router_add_external_gateway_endpoint = "add-external-gateway/"
router_add_internal_interface_endpoint = "add-internal-interface/"
server_list_endpoint = "servers/"
server_start_endpoint = "start/"
server_stop_endpoint = "stop/"
server_allocate_floating_ip_endpoint = "allocate-floating-ip/"