# Generated by Django 4.1 on 2022-09-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloudinfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_name', models.CharField(max_length=50)),
                ('minutes_to_live', models.IntegerField(default=10)),
                ('infra_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SHUTOFF', 'SHUTOFF')], default='SHUTOFF', max_length=10)),
                ('last_started', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=50)),
                ('network_cidr', models.CharField(max_length=20)),
                ('cloudinfra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cloudinfra')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=20)),
                ('flavor', models.CharField(max_length=20)),
                ('server_name', models.CharField(max_length=50)),
                ('floating_ip', models.BooleanField(default=False)),
                ('server_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SHUTOFF', 'SHUTOFF')], max_length=10)),
                ('cloudinfra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cloudinfra')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.network')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=50)),
                ('cloudinfra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cloudinfra')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.router'),
        ),
        migrations.AddField(
            model_name='cloudinfra',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
